server:
  port: ${PORT:{SERVER_PORT:0}}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/service_transport
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: herberT1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
  application:
    name: bike-msvc