
server:
  port: 8005

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Herbert-Loayza/repo-code-service
          search-paths: config-data
  application:
    name: config-service
